
name: Testes

# gatilhos dispara a execucao dos meus testes
# programados
# Acionados por eventos

on:
  push:
    branches: [ main ]

jobs:
  build:

# maquina ou ambiente em que sera executado
    runs-on: ubuntu-latest

# Passos
    steps:
    
# Download do codigo
    - uses: actions/checkout@v2
    
# setup da versao do node 
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
      
    - run: npm run report:merge
    
    - run: npm run report:mocha
    
# Github Pages-> publicar o relatorio
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: gh-pages
        FOLDER: mochawesome-report
